### ISSUE TITLE
Wrong render when I try to use only dashboard

### ISSUE THREAD

**Issue by mvillafuertem** [ScalablyTyped/SlinkyDemos#19]
Hi, I get a wrong render when I try to use only dashboard. Any suggestion of how could I fix it ?. Thanks

https://github.com/mvillafuertem/SlinkyDemos/commit/0602d090129c766eace3e2fc4f0f82f156d1a7b9

<img width="1552" alt="Screenshot 2020-06-07 at 17 05 09" src="https://user-images.githubusercontent.com/24855057/83972774-617eda00-a8e2-11ea-9a68-84970a90f55a.png">

**Comment by oyvindberg** [comment]
It magically started working when I put it inside the router, so I guess the styling is dependent upon being in some context. just imitate whatever the few levels up in the DOM tree does, I'm not about to dig into that CSS to figure out why :)

**Comment by oyvindberg** [comment]
My gut feeling would be that you'll need a `div` with say a flex context or similar. like I said, check what's there in the browser inspector

**Comment by mvillafuertem** [comment]
I have added a `List` component and it works. Maybe it isn't the right thing to do. Thanks!
