### ISSUE TITLE
antd/start and antd/dist failing

### ISSUE THREAD

**Issue by mcallisto** [ScalablyTyped/SlinkyDemos#24]
I just cloned the latest version of the repo.

While `sbt> react-router-dom/start` works fine, if I run `sbt> antd/start` I get the following error:

```
[IJ]sbt:slinkydemos> antd/start
[info] Writing scalajs.webpack.config.js
[info] Bundling the application with its NPM dependencies
[error] /.../SlinkyDemos/antd/target/scala-2.13/scalajs-bundler/main/node_modules/webpack-cli/bin/cli.js:74
[error] 				throw err;
[error] 				^
[error] Error: Cannot find module './_baseValues'
[error]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[error]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
[error]     at Module.require (internal/modules/cjs/loader.js:692:17)
...
```

The same happens with `sbt> antd/dist`.

@oyvindberg is it me or is it something you can reproduce on your side?

**Comment by oyvindberg** [comment]
I havent seen this. I don't suppose an `antd/clean` fixes anything?

**Comment by mcallisto** [comment]
> I havent seen this. I don't suppose an `antd/clean` fixes anything?

Unfortunately no, I tried it but it doesn't.

**Comment by mcallisto** [comment]
And I tried both from the SBT shell in IJ and from an independent SBT terminal.

**Comment by oyvindberg** [comment]
Ok. Is your node old for example? 

You can cd into antd/target/scala-2.13/scalajs-bundler/main (or something like that) and try to run webpack manually and see if it says anything interesting

**Comment by mcallisto** [comment]
> Ok. Is your node old for example?

```
$ node -v
v10.19.0
$ npm -v
6.14.4
```
Node seems indeed old, is v12 or v14 recommended?

> You can cd into antd/target/scala-2.13/scalajs-bundler/main (or something like that) and try to run webpack manually and see if it says anything interesting

I am there, but how exactly _to run webpack manually_?

**Comment by oyvindberg** [comment]
for instance like this (after running `fullOptJS` and `npmInstallDependencies` in sbt first):
```sh
$ node node_modules/.bin/webpack --mode production --config custom.webpack.config.js
```

I'm apparently on node 13.14.0, I don't have any idea if that matters.

**Comment by mcallisto** [comment]
> for instance like this (after running `fullOptJS` and `npmInstallDependencies` in sbt first):
> 
> ```shell
> $ node node_modules/.bin/webpack --mode production --config custom.webpack.config.js
> ```

Tried it, got the same identical error.

I can add that I am able to successfully `start` the following projects only:

1. office-ui-fabric-react
2. react-dnd
3. react-18next
4. react-mobx
5. react-router-dom
6. react-slick

The same identical reported error appears in:
1. material-ui
2. react-big-calendar
3. react-leaflet

**Comment by mcallisto** [comment]
By the way, got here because I wanted to add some stuff to the demo, especially regarding the antd `Select` component...

**Comment by mcallisto** [comment]
> I'm apparently on node 13.14.0, I don't have any idea if that matters.

My version 10.19.0 seems to be the default one on Ubuntu 20.04.
https://linuxize.com/post/how-to-install-node-js-on-ubuntu-20-04/
And so far I have never had problems, at least never noticed any.

I could try to install `nvm`, even if I am always a little bit wary about touching these things.

**Comment by oyvindberg** [comment]
Google error messages, newer webpack?

**Comment by mcallisto** [comment]
> Google error messages, newer webpack?

Let me add that other projects on my same machine, with

* antd 4.5.x bindings from beta 24
* `version in webpack := "4.42.1"`
* `version in startWebpackDevServer := "3.10.3"`

work just fine.

But if these demo work for everyone else, it must be something on my machine.
I also cannot see a pattern why some demo fails and other don't.
I will try to update `node`.

**Comment by oyvindberg** [comment]
https://forum.vuejs.org/t/vue-cli-project-wont-run-on-teamcity-vue-cli-3-0-0-build-fails/41869/4

**Comment by oyvindberg** [comment]
yarn cache clear

**Comment by mcallisto** [comment]
> yarn cache clear

:+1: now is working! Hope it will help someone in the future, thank you for nailing the solution.

The correct command is `yarn cache clean`.
