### ISSUE TITLE
Expo constants not working

### ISSUE THREAD

**Issue by mcallisto** [ScalablyTyped/SlinkyDemos#28]
As shown in the dedicated [`constants`](https://github.com/ScalablyTyped/SlinkyDemos/blob/74efd18c6af0d063d1a21bff05cdc5119504256b/react-native/src/main/scala/hello/world/Home.scala#L19) branch, for some reason is not possible to obtain the correct value for any of the [Expo Constants](https://docs.expo.io/versions/v37.0.0/sdk/constants/).

In the **Home** page of the demo I obtain
```
The status bar is 0 pixels high
Expo version is null
```

Anyone has any idea on how to get them right?

**Comment by oyvindberg** [comment]
What if you go through `typings.expoConstants.mod.default` instead?

**Comment by mcallisto** [comment]
> What if you go through `typings.expoConstants.mod.default` instead?

Success :+1: !

I know I already look fairly stupid, but I will add to that :wink:... I searched for an alternative location in the `typings.expoConstants` for days before venturing to ask and still I overlooked the solution...
