### ISSUE TITLE
expo-av playing sound from an url

### ISSUE THREAD

**Issue by mcallisto** [ScalablyTyped/SlinkyDemos#31]
Hi @oyvindberg, I have been also trying to use the converted [Expo Audio lib](https://docs.expo.io/versions/v38.0.0/sdk/audio/#playing-sounds) to play a sound from the internet.

Made some experiment on a dedicated [expo-av branch](https://github.com/ScalablyTyped/SlinkyDemos/blob/expo-av/react-native/src/main/scala/hello/world/PlayAudio.scala).

To begin with, the `createSound` method wants an `AVPlaybackSource` that is defined as
```
type AVPlaybackSource = scala.scalajs.js.|[scala.scalajs.js.|[scala.Double, typings.expoAv.anon.Headers], typings.expoAsset.mod.Asset]
```
it seems there is no way to pass a simple `uri: String`.

Any suggestion on how to solve this?

**Comment by oyvindberg** [comment]
Isn't there some javascript example out there you can translate?

There is some asset handling (for fonts) in the react-native demo already, might have to do something similar.
You can get an `Asset` by going through this https://github.com/ScalablyTyped/SlinkyTyped/blob/master/e/expo-asset/src/main/scala/typingsSlinky/expoAsset/mod.scala#L24

**Comment by mcallisto** [comment]
> There is some asset handling (for fonts) in the react-native demo already, might have to do something similar.
> You can get an `Asset` by going through this https://github.com/ScalablyTyped/SlinkyTyped/blob/master/e/expo-asset/src/main/scala/typingsSlinky/expoAsset/mod.scala#L24

An `Asset.uri` in `expo-asset` does not seem free to point to a generic internet resource, but only to Expo's asset server, see https://docs.expo.io/versions/v38.0.0/sdk/asset/#api

**Comment by mcallisto** [comment]
> Isn't there some javascript example out there you can translate?

Yes, other than those in the [Expo Audio lib](https://docs.expo.io/versions/v38.0.0/sdk/audio/#playing-sounds), there seems to be many usages in the wild, in [JavaScript](https://github.com/search?q=expo-av+Audio.Sound+uri+language%3AJavaScript&type=Code) and also in [TypeScript](https://github.com/search?q=expo-av+Audio.Sound+uri++language%3ATypeScript&type=Code).

Being able to translate them, not sure.
But if that is the only option I can try and learn.
My first idea is always to report to you and check if the converted typings are sound and/or useful.

Just for having the whole picture, I have also found a tiny bit of a manual facade:
https://github.com/scommons/scommons-react-native/tree/b0d070ec6240eeeaa7ec82a187b99fa3e36391c0/expo/src/main/scala/scommons/expo/av

**Comment by oyvindberg** [comment]
It looks pretty straightforward to use what's there:

```scala
  val soundObject = new typings.expoAv.mod.Audio.Sound
  soundObject
    .loadAsync(
      typings.expoAv.anon.Headers(uri = "https://..."),
      typings.expoAv.aVMod.AVPlaybackStatusToSet().setShouldPlay(true) // optional, but you can set a bunch of stuff here
    )
    .toFuture
    .flatMap((status: typings.expoAv.aVMod.AVPlaybackStatus) => soundObject.playAsync().toFuture)

```

I didnt run it, but I guess there is a fair chance it might work

**Comment by mcallisto** [comment]
> I didnt run it, but I guess there is a fair chance it might work

:+1: is working, thank you! Tomorrow I will try to expand on that and enhance the demo.

**Comment by mcallisto** [comment]
Ok, basic demo done, PR opened #32
