### ISSUE TITLE
i18next interpolation

### ISSUE THREAD

**Issue by mcallisto** [ScalablyTyped/SlinkyDemos#37]
While [plurals](https://www.i18next.com/translation-function/plurals) and [context](https://www.i18next.com/translation-function/context) are both fine in the current demo, I cannot find a way to make [interpolation](https://www.i18next.com/translation-function/interpolation) work.

I wrote some (failing...) code around here
https://github.com/ScalablyTyped/SlinkyDemos/blob/4ba8a857f4acfdc573f0109301b52e52a240d484/react-i18n/src/main/scala/demo/App.scala#L37
getting always the same error
`i18next::interpolator: missed to pass in variable author for interpolating The author is {{author}}`

**Comment by oyvindberg** [comment]
have a look at master now, think I fixed it

**Comment by mcallisto** [comment]
Great, thank you!
