### ISSUE TITLE
antd RangePicker value

### ISSUE THREAD

**Issue by mcallisto** [ScalablyTyped/SlinkyDemos#39]
I have added an example of the `RangePicker` component, see https://ant.design/components/time-picker/#components-time-picker-demo-range-picker.

I think it is really well done, very satisfied about the quality of this library.

I have just one issue, I cannot set the current `value`, see
https://github.com/ScalablyTyped/SlinkyDemos/blob/29f6da24d7ba5ec226b230ad962220856fcf34d6/antd/src/main/scala/demo/App.scala#L449

The root problem is that I am not able to create a `Moment`.

**Comment by oyvindberg** [comment]
There, I pushed a quick fix

**Comment by mcallisto** [comment]
Great, thank you!
