### ISSUE TITLE
Using moment.js or days.js for localized duration

### ISSUE THREAD

**Issue by mcallisto** [ScalablyTyped/SlinkyDemos#41]
I cannot find the way in React Native to localize **`moment.js`** duration strings (or other dates/times objects).
The issue seems to be how to _set_ the needed locale data, that I am convinced is stored in the library.
https://momentjs.com/docs/#/i18n/loading-into-nodejs/
https://momentjs.com/docs/#/i18n/getting-locale/

I also imported **`day.js`** to try an alternative, but stuck at the same point.
https://day.js.org/docs/en/i18n/loading-into-nodejs

Any idea? I have written a small exercise with https://github.com/ScalablyTyped/SlinkyDemos/commit/38dcd39980b6fb01df3438def9af37421eca2b1f in the [`native-duration-locale` branch](https://github.com/ScalablyTyped/SlinkyDemos/compare/native-duration-locale).

I was coming from `antd` for React (web) that bundles **`moment.js`** and seems to have all locales already _set_. The code I am proposing would have produced localized durations in Spanish, French and Italian.

But here, as shown below, nothing happens:

![Screenshot_1611357047](https://user-images.githubusercontent.com/122379/105558862-f585a080-5d0f-11eb-8bd4-4d87a474274a.png)

**Comment by oyvindberg** [comment]
No idea really, havent had this problem before. There seems to be loads of ideas over in https://github.com/moment/moment/issues/4422 - have you checked it?

**Comment by mcallisto** [comment]
Thanks for the pointer.

I can make it work already by adding these imports to `App.js`:
```
import React from 'react';
import {Text, View} from 'react-native';
// starts addition
import 'moment/locale/es';
import 'moment/locale/fr';
import 'moment/locale/it';
...
```

Is it possible to do the same from scala.js? I tried to play with `@JSImport` https://www.scala-js.org/doc/interoperability/facade-types.html but did not succeed.

**Comment by oyvindberg** [comment]
```scala
@JSImport("moment/locale/es", JSImport.Namespace)
@js.native
object es extends js.Object
```
and touch it before you do anything else in your app?

**Comment by mcallisto** [comment]
Great, done, it's working, see https://github.com/ScalablyTyped/SlinkyDemos/compare/native-duration-locale?expand=1.

I think it is worth adding to the demo, what do you think, should I prepare a PR?

**Comment by oyvindberg** [comment]
Yes sure, can't hurt :)

**Comment by mcallisto** [comment]
:+1: sent to your review, ready #42 to be squashed and merged

**Comment by oyvindberg** [comment]
thanks :)
